# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballteam',
            name='roster',
            field=models.IntegerField(max_length=88),
        ),
    ]
